slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.1
    transform_publish_period: 0.02
    map_update_interval: 5.0
    map_start_at_dock: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    map_file_name: map
    map_start_pose: [0.0, 0.0, 0.0]
    debug_logging: false
    throttle_scans: 1
